### Test route, should return "Hello World"
http://localhost:5001

### This should mint the NFT to the provided address and then send the telegram message to the userID
POST http://localhost:5001/mint-nft
Content-Type: application/json

{
    "userId": 1051514609,
    "address": "0x5C2CF54690d809F8F03b5a96F8A2Adf50A51d7D8"
}